version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=dynamic_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    ports:
      - "127.0.0.1:5432:5432"
